-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 19:53:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock-market-charting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock-market-charting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock-market-charting` DEFAULT CHARACTER SET utf8 ;
USE `stock-market-charting` ;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`company` (
  `co_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `co_name` VARCHAR(255) NULL,
  `co_turnover` FLOAT NULL,
  `co_sector` VARCHAR(20) NULL,
  `co_ceo` VARCHAR(25) NULL,
  `co_board_of_directors` VARCHAR(255) NULL,
  `co_brief_writeup` VARCHAR(255) NULL,
  `co_stock_code` BIGINT(10)  NOT NULL,
  PRIMARY KEY (`co_id`))
ENGINE = InnoDB;
 


-- -----------------------------------------------------
-- Table `stock-market-charting`.`stock_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`stock_exchange` (
  `se_id` BIGINT(10) NOT NULL,
  `se_stock_exchange` VARCHAR(50) NOT NULL,
  `se_brief` VARCHAR(255) NULL,
  `se_contact_address` VARCHAR(255) NULL,
  `se_remark` VARCHAR(45) NULL,
  PRIMARY KEY (`se_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `stock-market-charting`.`company_stock_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`company_stock_exchange` (
`cs_id` INT NOT NULL AUTO_INCREMENT,
  `cs_co_id` BIGINT(10) NOT NULL,
  `cs_se_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`cs_id`),
  INDEX `fk_company_has_stock_exchange_stock_exchange1_idx` (`cs_se_id` ASC),
  INDEX `fk_company_has_stock_exchange_company1_idx` (`cs_co_id` ASC),
  CONSTRAINT `fk_company_has_stock_exchange_company1`
    FOREIGN KEY (`cs_co_id`)
    REFERENCES `stock-market-charting`.`company` (`co_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_has_stock_exchange_stock_exchange1`
    FOREIGN KEY (`cs_se_id`)
    REFERENCES `stock-market-charting`.`stock_exchange` (`se_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(60) NULL,
  `us_password` VARCHAR(60) NULL,
   `us_email` VARCHAR(60) NULL,
   `us_mobile_number` VARCHAR(45) NULL,
   `us_confirmed` boolean NULL,
   `us_ro_id` INT(11) NOT NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `stock-market-charting`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`role` (
  `ro_id` INT NOT NULL AUTO_INCREMENT,
  `ro_name` VARCHAR(60) NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock-market-charting`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock-market-charting`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_us_id` INT NULL,
  `ur_ro_id` INT NULL,
  PRIMARY KEY (`ur_id`),
  INDEX `ur_us_fk_idx` (`ur_us_id` ASC),
  INDEX `ur_ro_fk_idx` (`ur_ro_id` ASC),
  CONSTRAINT `ur_us_fk`
    FOREIGN KEY (`ur_us_id`)
    REFERENCES `stock-market-charting`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ur_ro_fk`
    FOREIGN KEY (`ur_ro_id`)
    REFERENCES `stock-market-charting`.`role` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
